name: Run API Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate report
        run: pytest --junitxml=report.xml

      - name: Upload test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.xml
